theory ExecutableIdentityExpansionExamples
  imports ExecutableIdentityExpansion
begin

text \<open>
  A concrete reverse-and-invert executable adjoint cannot yet be instantiated
  from the current abstract placement locale. The missing semantic interface is
  a law of the intended shape

    dagger (place_gate n G params) = place_gate n (dagger G) params,

  together with a total executable inverse operation satisfying a law of the
  intended shape

    denote_gate_id (inverse_gate_id g) = dagger (denote_gate_id g).

  This theory therefore completes the concrete Base and Compose fragment and
  keeps Adjoint expressions explicitly excluded.
\<close>


section \<open>Concrete Certified Base Identities\<close>

definition hh_identity_circuit_id ::
  (*
    """
    Purpose:
      Defines a concrete one-qubit identity circuit containing two Hadamard gates.

    Arguments:
      None.

    Assumptions:
      The executable inverse table keeps the Hadamard self-inverse pair at index three.

    Conclusion:
      Returns the circuit generated by inserting the certified Hadamard inverse pair
      into an empty one-qubit circuit.
    """
  *)
  quantum_circuit_id
where
  "hh_identity_circuit_id =
     apply_step_id
       (empty_circuit_id 1)
       (InsertInverseId 0 3 [0])"


definition xx_identity_circuit_id ::
  (*
    """
    Purpose:
      Defines a concrete one-qubit identity circuit containing two Pauli-X gates.

    Arguments:
      None.

    Assumptions:
      The executable inverse table keeps the Pauli-X self-inverse pair at index zero.

    Conclusion:
      Returns the circuit generated by inserting the certified Pauli-X inverse pair
      into an empty one-qubit circuit.
    """
  *)
  quantum_circuit_id
where
  "xx_identity_circuit_id =
     apply_step_id
       (empty_circuit_id 1)
       (InsertInverseId 0 0 [0])"


definition basic_1q_identity_basis ::
  (*
    """
    Purpose:
      Defines a small concrete basis of certified one-qubit identities.

    Arguments:
      None.

    Assumptions:
      Each member is generated by the existing verified inverse-insertion pipeline.

    Conclusion:
      Returns a basis containing the Hadamard and Pauli-X self-inverse identities.
    """
  *)
  "quantum_circuit_id list"
where
  "basic_1q_identity_basis =
     [hh_identity_circuit_id, xx_identity_circuit_id]"


context obfuscation_semantics_u3
begin

lemma hh_identity_circuit_id_valid:
  (*
    """
    Purpose:
      Proves structural validity of the concrete Hadamard identity circuit.

    Arguments:
      None.

    Assumptions:
      Uses the existing validity theorem for executable obfuscation steps.

    Conclusion:
      The two-Hadamard circuit is a valid one-qubit executable circuit.
    """
  *)
  "valid_quantum_circuit_id hh_identity_circuit_id"
  unfolding hh_identity_circuit_id_def
  by (rule valid_apply_step_id[OF valid_empty_circuit_id])


lemma xx_identity_circuit_id_valid:
  (*
    """
    Purpose:
      Proves structural validity of the concrete Pauli-X identity circuit.

    Arguments:
      None.

    Assumptions:
      Uses the existing validity theorem for executable obfuscation steps.

    Conclusion:
      The two-Pauli-X circuit is a valid one-qubit executable circuit.
    """
  *)
  "valid_quantum_circuit_id xx_identity_circuit_id"
  unfolding xx_identity_circuit_id_def
  by (rule valid_apply_step_id[OF valid_empty_circuit_id])


lemma hh_identity_circuit_id_semantics:
  (*
    """
    Purpose:
      Proves exact identity semantics for the concrete Hadamard identity circuit.

    Arguments:
      None.

    Assumptions:
      Reuses the denotation bridge and semantic preservation theorem for the
      existing executable inverse-insertion step.

    Conclusion:
      The two-Hadamard circuit has exactly the same denotation as the empty
      one-qubit circuit.
    """
  *)
  "eval_circuit (denote_circuit_id hh_identity_circuit_id) =
   eval_circuit (denote_circuit_id (empty_circuit_id 1))"
proof -
  have bridge:
    "denote_circuit_id
       (apply_step_id (empty_circuit_id 1) (InsertInverseId 0 3 [0])) =
     apply_denoted_step_id
       (empty_circuit_id 1) (InsertInverseId 0 3 [0])"
    by (rule denote_apply_step_id[OF valid_empty_circuit_id])
  have preserve:
    "eval_circuit
       (apply_denoted_step_id
         (empty_circuit_id 1) (InsertInverseId 0 3 [0])) =
     eval_circuit (denote_circuit_id (empty_circuit_id 1))"
    by (rule preserve_apply_denoted_step_id[OF valid_empty_circuit_id])
  show ?thesis
    using bridge preserve
    by (simp add: hh_identity_circuit_id_def)
qed


lemma xx_identity_circuit_id_semantics:
  (*
    """
    Purpose:
      Proves exact identity semantics for the concrete Pauli-X identity circuit.

    Arguments:
      None.

    Assumptions:
      Reuses the denotation bridge and semantic preservation theorem for the
      existing executable inverse-insertion step.

    Conclusion:
      The two-Pauli-X circuit has exactly the same denotation as the empty
      one-qubit circuit.
    """
  *)
  "eval_circuit (denote_circuit_id xx_identity_circuit_id) =
   eval_circuit (denote_circuit_id (empty_circuit_id 1))"
proof -
  have bridge:
    "denote_circuit_id
       (apply_step_id (empty_circuit_id 1) (InsertInverseId 0 0 [0])) =
     apply_denoted_step_id
       (empty_circuit_id 1) (InsertInverseId 0 0 [0])"
    by (rule denote_apply_step_id[OF valid_empty_circuit_id])
  have preserve:
    "eval_circuit
       (apply_denoted_step_id
         (empty_circuit_id 1) (InsertInverseId 0 0 [0])) =
     eval_circuit (denote_circuit_id (empty_circuit_id 1))"
    by (rule preserve_apply_denoted_step_id[OF valid_empty_circuit_id])
  show ?thesis
    using bridge preserve
    by (simp add: xx_identity_circuit_id_def)
qed


lemma hh_identity_circuit_id_phase_identity:
  (*
    """
    Purpose:
      Lifts exact Hadamard-pair semantics to certified phase-identity semantics.

    Arguments:
      None.

    Assumptions:
      The exact semantic equality of the Hadamard-pair circuit is available.

    Conclusion:
      The concrete Hadamard-pair circuit is an identity up to global phase.
    """
  *)
  "phase_identity_circuit 1 hh_identity_circuit_id"
proof -
  have qubits: "num_qubits_id hh_identity_circuit_id = 1"
    by (simp add:
        hh_identity_circuit_id_def
        insert_inverse_circuit_id_def
        can_insert_inverse_circuit_id_def
        can_insert_at_id_def
        valid_params_for_gate_seq_id_def
        inverses_id_def
        insert_instructions_at_id_def
        empty_circuit_id_def
        make_quantum_circuit_id_def)

  have empty_qubits: "num_qubits_id (empty_circuit_id 1) = 1"
    by (simp add:
        empty_circuit_id_def
        make_quantum_circuit_id_def)

  have equivalence:
    "equiv_upto_global_phase
       (eval_circuit (denote_circuit_id hh_identity_circuit_id))
       (eval_circuit (denote_circuit_id (empty_circuit_id 1)))"
    using hh_identity_circuit_id_semantics
    by (rule equal_matrices_are_equivalent)

  show ?thesis
    using qubits empty_qubits equivalence
    by (simp add: phase_identity_circuit_def phase_equiv_circuit_def)
qed


lemma xx_identity_circuit_id_phase_identity:
  (*
    """
    Purpose:
      Lifts exact Pauli-X-pair semantics to certified phase-identity semantics.

    Arguments:
      None.

    Assumptions:
      The exact semantic equality of the Pauli-X-pair circuit is available.

    Conclusion:
      The concrete Pauli-X-pair circuit is an identity up to global phase.
    """
  *)
  "phase_identity_circuit 1 xx_identity_circuit_id"
proof -
  have qubits: "num_qubits_id xx_identity_circuit_id = 1"
    by (simp add:
        xx_identity_circuit_id_def
        insert_inverse_circuit_id_def
        can_insert_inverse_circuit_id_def
        can_insert_at_id_def
        valid_params_for_gate_seq_id_def
        inverses_id_def
        insert_instructions_at_id_def
        empty_circuit_id_def
        make_quantum_circuit_id_def)
  have empty_qubits: "num_qubits_id (empty_circuit_id 1) = 1"
    by (simp add:
        empty_circuit_id_def
        make_quantum_circuit_id_def)

  have equivalence:
    "equiv_upto_global_phase
       (eval_circuit (denote_circuit_id xx_identity_circuit_id))
       (eval_circuit (denote_circuit_id (empty_circuit_id 1)))"
    using xx_identity_circuit_id_semantics
    by (rule equal_matrices_are_equivalent)

  show ?thesis
    using qubits empty_qubits equivalence
    by (simp add: phase_identity_circuit_def phase_equiv_circuit_def)
qed


lemma basic_1q_identity_basis_valid:
  (*
    """
    Purpose:
      Certifies the concrete one-qubit identity basis.

    Arguments:
      None.

    Assumptions:
      Both basis members are structurally valid and phase identities.

    Conclusion:
      Every circuit in the concrete basis is a valid one-qubit phase identity.
    """
  *)
  "valid_identity_basis 1 basic_1q_identity_basis"
  using hh_identity_circuit_id_valid xx_identity_circuit_id_valid
        hh_identity_circuit_id_phase_identity
        xx_identity_circuit_id_phase_identity
  by (simp add: valid_identity_basis_def basic_1q_identity_basis_def)


end


section \<open>Concrete Base and Compose Generation\<close>

fun adjoint_free_identity_expr ::
  (*
    """
    Purpose:
      Identifies the currently executable Base and Compose fragment of identity expressions.

    Arguments:
      expr:
        The identity expression being inspected.

    Assumptions:
      None.

    Conclusion:
      Returns true exactly when the expression contains no Adjoint constructor.
    """
  *)
  "identity_expr \<Rightarrow> bool"
where
  "adjoint_free_identity_expr (Base i) = True"
| "adjoint_free_identity_expr (Adjoint expr) = False"
| "adjoint_free_identity_expr (Compose left right) =
     (adjoint_free_identity_expr left \<and>
      adjoint_free_identity_expr right)"


context obfuscation_semantics_u3
begin



fun eval_base_compose_identity_expr ::
  (*
    """
    Purpose:
      Evaluates the concrete Base and Compose fragment of identity expressions.

    Arguments:
      qbit_count:
        The qubit count used by the unreachable Adjoint fallback.

      basis:
        The concrete executable identity basis.

      expr:
        The adjoint-free expression being evaluated.

    Assumptions:
      Sound use requires the expression to be adjoint-free and all base indices
      to be valid.

    Conclusion:
      Returns the executable circuit generated by base lookup and circuit composition.
    """
  *)
  "nat \<Rightarrow> quantum_circuit_id list \<Rightarrow> identity_expr \<Rightarrow>
   quantum_circuit_id"
where
  "eval_base_compose_identity_expr qbit_count basis (Base i) =
     (if i < length basis then basis ! i else empty_circuit_id qbit_count)"
| "eval_base_compose_identity_expr qbit_count basis (Adjoint expr) =
     empty_circuit_id qbit_count"
| "eval_base_compose_identity_expr qbit_count basis (Compose left right) =
     append_circuit_id
       (eval_base_compose_identity_expr qbit_count basis left)
       (eval_base_compose_identity_expr qbit_count basis right)"


theorem eval_base_compose_identity_expr_sound:
  (*
    """
    Purpose:
      Proves generator soundness for the concrete adjoint-free expression fragment.

    Arguments:
      n:
        The common number of qubits.

      basis:
        The certified executable identity basis.

      expr:
        The well-formed adjoint-free identity expression.

    Assumptions:
      The basis is valid, every base index is in bounds, and the expression uses
      only Base and Compose.

    Conclusion:
      Evaluating the expression produces a structurally valid phase identity.
    """
  *)
  assumes basis_valid: "valid_identity_basis n basis"
  assumes expr_valid: "valid_identity_expr (length basis) expr"
  assumes adjoint_free: "adjoint_free_identity_expr expr"
  shows
    "valid_quantum_circuit_id
       (eval_base_compose_identity_expr n basis expr) \<and>
     phase_identity_circuit n
       (eval_base_compose_identity_expr n basis expr)"
  using expr_valid adjoint_free
proof (induction expr)
  case (Base i)
  then have i_lt: "i < length basis" by simp
  have member:
    "valid_quantum_circuit_id (basis ! i) \<and>
     phase_identity_circuit n (basis ! i)"
    using basis_valid i_lt
    by (auto simp add: valid_identity_basis_def list_all_iff)
  show ?case
    using i_lt member by simp
next
  case (Adjoint expr)
  then show ?case by simp
next
  case (Compose left right)
  then have left:
    "valid_quantum_circuit_id
       (eval_base_compose_identity_expr n basis left) \<and>
     phase_identity_circuit n
       (eval_base_compose_identity_expr n basis left)"
    by simp
  from Compose have right:
    "valid_quantum_circuit_id
       (eval_base_compose_identity_expr n basis right) \<and>
     phase_identity_circuit n
       (eval_base_compose_identity_expr n basis right)"
    by simp
  show ?case
    by (simp add: left phase_identity_append right)
qed

end


definition example_base_compose_identity_expr ::
  (*
    """
    Purpose:
      Defines a concrete generated identity expression from both one-qubit basis members.

    Arguments:
      None.

    Assumptions:
      The concrete basis stores the Hadamard identity at index zero and the
      Pauli-X identity at index one.

    Conclusion:
      Returns an expression composing the two concrete certified base identities.
    """
  *)
  identity_expr
where
  "example_base_compose_identity_expr = Compose (Base 0) (Base 1)"


lemma example_base_compose_identity_expr_adjoint_free:
  (*
    """
    Purpose:
      Proves that the concrete example stays inside the supported expression fragment.

    Arguments:
      None.

    Assumptions:
      None.

    Conclusion:
      The example contains only Base and Compose constructors.
    """
  *)
  "adjoint_free_identity_expr example_base_compose_identity_expr"
  by (simp add: example_base_compose_identity_expr_def)


context obfuscation_semantics_u3
begin

lemma example_base_compose_identity_expr_valid:
  (*
    """
    Purpose:
      Proves index validity of the concrete generated identity expression.

    Arguments:
      None.

    Assumptions:
      The concrete identity basis contains two entries.

    Conclusion:
      Every base reference in the example expression is within the basis bounds.
    """
  *)
  "valid_identity_expr
     (length basic_1q_identity_basis)
     example_base_compose_identity_expr"
  by (simp add:
      basic_1q_identity_basis_def
      example_base_compose_identity_expr_def)


theorem example_generated_identity_sound:
  (*
    """
    Purpose:
      Proves semantic soundness of the concrete generated identity expression.

    Arguments:
      None.

    Assumptions:
      Uses the certified one-qubit basis and the valid adjoint-free example expression.

    Conclusion:
      The generated executable circuit is structurally valid and is an identity
      up to global phase.
    """
  *)
  "valid_quantum_circuit_id
     (eval_base_compose_identity_expr
       1 basic_1q_identity_basis example_base_compose_identity_expr) \<and>
   phase_identity_circuit 1
     (eval_base_compose_identity_expr
       1 basic_1q_identity_basis example_base_compose_identity_expr)"
  using basic_1q_identity_basis_valid
        example_base_compose_identity_expr_valid
        example_base_compose_identity_expr_adjoint_free
  apply simp
  by (meson executable_u3_basis_gate_axioms executable_u3_basis_gate_def
      gate_placement_axioms id_is_gate obfuscation_semantics_def
      obfuscation_semantics_u3.eval_base_compose_identity_expr_sound
      obfuscation_semantics_u3_def)
  

definition example_identity_prefix_id ::
  (*
    """
    Purpose:
      Defines the executable prefix used by the end-to-end insertion example.

    Arguments:
      None.

    Assumptions:
      None.

    Conclusion:
      Returns a valid one-qubit circuit containing one Hadamard gate.
    """
  *)
  quantum_circuit_id
where
  "example_identity_prefix_id = h_id (empty_circuit_id 1) 0"


definition example_identity_suffix_id ::
  (*
    """
    Purpose:
      Defines the executable suffix used by the end-to-end insertion example.

    Arguments:
      None.

    Assumptions:
      None.

    Conclusion:
      Returns a valid one-qubit circuit containing one Pauli-X gate.
    """
  *)
  quantum_circuit_id
where
  "example_identity_suffix_id = x_id (empty_circuit_id 1) 0"


lemma example_identity_prefix_id_valid:
  (*
    """
    Purpose:
      Proves validity of the concrete insertion prefix.

    Arguments:
      None.

    Assumptions:
      Uses the executable Hadamard append validity theorem.

    Conclusion:
      The prefix is a valid one-qubit executable circuit.
    """
  *)
  "valid_quantum_circuit_id example_identity_prefix_id"
  by (simp add:
      example_identity_prefix_id_def
      h_id_def append_gate_id_def append_instruction_id_def
      make_instruction_id_def valid_quantum_circuit_id_def
      valid_instruction_id_def valid_qubits_id_def
      empty_circuit_id_def make_quantum_circuit_id_def)


lemma example_identity_suffix_id_valid:
  (*
    """
    Purpose:
      Proves validity of the concrete insertion suffix.

    Arguments:
      None.

    Assumptions:
      Uses the executable Pauli-X append validity theorem.

    Conclusion:
      The suffix is a valid one-qubit executable circuit.
    """
  *)
  "valid_quantum_circuit_id example_identity_suffix_id"
  by (simp add:
      example_identity_suffix_id_def
      x_id_def append_gate_id_def append_instruction_id_def
      make_instruction_id_def valid_quantum_circuit_id_def
      valid_instruction_id_def valid_qubits_id_def
      empty_circuit_id_def make_quantum_circuit_id_def)

theorem example_generated_identity_insertion:
  (*
    """
    Purpose:
      Demonstrates the complete concrete certified identity-expansion pipeline.

    Arguments:
      None.

    Assumptions:
      The concrete basis, generated expression, prefix, and suffix have already
      been certified.

    Conclusion:
      Inserting the generated identity between the example prefix and suffix
      preserves the complete circuit up to global phase.
    """
  *)
  "phase_equiv_circuit 1
     (append_circuit_id
       (append_circuit_id
         example_identity_prefix_id
         (eval_base_compose_identity_expr
           1 basic_1q_identity_basis example_base_compose_identity_expr))
       example_identity_suffix_id)
     (append_circuit_id
       example_identity_prefix_id
       example_identity_suffix_id)"
proof -
  have generated_valid:
    "valid_quantum_circuit_id
       (eval_base_compose_identity_expr
         1 basic_1q_identity_basis example_base_compose_identity_expr)"
    using example_generated_identity_sound by simp

  have generated_identity:
    "phase_identity_circuit 1
       (eval_base_compose_identity_expr
         1 basic_1q_identity_basis example_base_compose_identity_expr)"
    using example_generated_identity_sound by simp

  have generated_n:
    "num_qubits_id
       (eval_base_compose_identity_expr
         1 basic_1q_identity_basis example_base_compose_identity_expr) = 1"
    using generated_identity
    by (simp add: phase_identity_circuit_def phase_equiv_circuit_def)

  have prefix_n:
    "num_qubits_id example_identity_prefix_id = 1"
    by (simp add:
        example_identity_prefix_id_def
        h_id_def append_gate_id_def append_instruction_id_def
        empty_circuit_id_def make_quantum_circuit_id_def)

  have suffix_n:
    "num_qubits_id example_identity_suffix_id = 1"
    by (simp add:
        example_identity_suffix_id_def
        x_id_def append_gate_id_def append_instruction_id_def
        empty_circuit_id_def make_quantum_circuit_id_def)

  show ?thesis
    using phase_identity_insertion
    apply simp
  proof -
    have f1: "obfuscation_semantics place_gate 1 (Quantum.Id 1)"
      using gate_placement_axioms obfuscation_semantics.intro by fastforce
    have "\<forall>n m f fa. executable_u3_basis_gate n m f fa = (gate n m \<and> executable_u3_basis_gate_axioms f fa)"
      using executable_u3_basis_gate_def by presburger
    then have "executable_u3_basis_gate 1 (Quantum.Id 1) denote_basis_id denote_inv_basis_id"
      using executable_u3_basis_gate_axioms by auto
    then show "phase_equiv_circuit (Suc 0) (append_circuit_id (append_circuit_id example_identity_prefix_id (eval_base_compose_identity_expr (Suc 0) basic_1q_identity_basis example_base_compose_identity_expr)) example_identity_suffix_id) (append_circuit_id example_identity_prefix_id example_identity_suffix_id)"
      using f1 by (metis (no_types) One_nat_def example_generated_identity_sound example_identity_prefix_id_valid example_identity_suffix_id_valid generated_n obfuscation_semantics_u3.intro obfuscation_semantics_u3.phase_identity_insertion prefix_n suffix_n)
  qed
qed

end


end
